# Generated by Django 4.1.7 on 2023-03-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_book_is_active"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="Following",
            field=models.ManyToManyField(related_name="users", to="books.book"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
    ]
