# Generated by Django 4.1.7 on 2023-03-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_book_is_active"),
        ("users", "0002_user_following_user_is_blocked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="Following",
            field=models.ManyToManyField(related_name="followings", to="books.book"),
        ),
    ]
