# Generated by Django 4.1.7 on 2023-03-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_following"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "email already exists"},
                max_length=200,
                unique=True,
            ),
        ),
        migrations.AlterModelTable(
            name="user",
            table="User",
        ),
    ]
