# Generated by Django 4.1.7 on 2023-03-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="blocked_until",
            field=models.DateField(default=None, null=True),
        ),
    ]
