# Generated by Django 4.1.7 on 2023-03-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_options_alter_user_email_alter_user_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["username"]},
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="user",
            unique_together={("username", "email")},
        ),
    ]
