# Generated by Django 4.1.7 on 2023-03-08 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="following",
            field=models.ManyToManyField(
                null=True,
                related_name="following_books",
                through="books.BookFollowing",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
