# Generated by Django 4.1.7 on 2023-03-10 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_rename_bookfollowing_following"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="following",
            name="book_title",
        ),
        migrations.RemoveField(
            model_name="following",
            name="user_email",
        ),
    ]
