# Generated by Django 4.1.7 on 2023-03-13 06:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0006_book_following_book"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="Following_book",
        ),
    ]
