<<<<<<< HEAD
# Generated by Django 4.1.7 on 2023-03-13 12:39
=======
# Generated by Django 4.1.7 on 2023-03-13 21:52
>>>>>>> feat/users

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        ("copies", "0001_initial"),
        ("books", "0002_initial"),
>>>>>>> feat/users
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("copies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="borrowings_copies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="copy",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book_copies",
                to="books.book",
            ),
        ),
        migrations.AddField(
            model_name="copy",
            name="users",
            field=models.ManyToManyField(
                related_name="borroweds_copies",
                through="copies.Loan",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
