# Generated by Django 4.1.7 on 2023-03-08 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("copies", "0002_borrowings"),
    ]

    operations = [
        migrations.AddField(
            model_name="copy",
            name="borrowings",
            field=models.ManyToManyField(
                related_name="borrowings_copy",
                through="copies.Borrowings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
